#!/bin/bash

alias dm="busybox devmem"


rd () {
	busybox devmem `printf "0x%X" $(( $1 + $2 ))`
}

wr (){
	busybox devmem `printf "0x%X" $(( $1 +  $2 ))` 32  $3
}

TIMER6_BASE="0x48048000"
TIMER5_BASE="0x48046000"
TIMER_NAME="TIMER_6"
CLOCK_CTRL_BASE="0x44e00000"
CLOCK_CTRL_TIM6_OFFSET=0xf0
CLOCK_CTRL_TIM5_OFFSET=0xec


GPIO0_BASE="0x44e07000"
GPIO0_IRQ_RAW_OFFSET="0x24"
GPIO_IRQ_SET0_OFFSET="0x34"

TIM_REG_NAME=("TIDR" "TIOCP_CFG" "IRQ_RAW" "IRQSTATUS" "TCLR" "TCRR" "TLDR" "TTGR" "TMAR" "TCAR1" "TSICR" "TCAR2")
TIM_REG_OFFSET=(0 0x10 0x24 0x28 0x38 0x3c 0x40 0x44 0x4c 0x50 0x54 0x58 )
VALID_IDX="0 1 2 3 4 5 6 7 8 9 10 11"

dump_regs6 () {
	for idx in $VALID_IDX
	do
		offset=${TIM_REG_OFFSET[idx]}
		printf "0x%X - \t%s\t - \t " $(( $TIMER6_BASE + $offset )) ${TIM_REG_NAME[idx]}
		rd $TIMER6_BASE $offset
	done
}
dump_regs5 () {
	for idx in $VALID_IDX
	do
		offset=${TIM_REG_OFFSET[idx]}
		printf "0x%X - \t%s\t - \t " $(( $TIMER5_BASE + $offset )) ${TIM_REG_NAME[idx]}
		rd $TIMER6_BASE $offset
	done
}


echo "ENABLING TIMER CLOCK"
wr $CLOCK_CTRL_BASE $CLOCK_CTRL_TIM5_OFFSET 0x00000002
wr $CLOCK_CTRL_BASE $CLOCK_CTRL_TIM6_OFFSET 0x00000002


echo "Resettings timers"
wr $TIMER5_BASE "0x54" "0x00000002"
wr $TIMER6_BASE "0x54" "0x00000002"



echo "Setting up timer for input capture:"
wr $TIMER5_BASE "0x38" "0x00000103"
wr $TIMER6_BASE "0x38" "0x00000103"

echo "GETTING TIMER REGISTERS"
echo "Timer5"
dump_regs5
echo "Timer 6"
dump_regs6





echo "Changing timer 5 and 6 event mux to gpioINT0A (17<<8+17 = 4369)"
python pyioctl /dev/event_mux 0 4369
echo "TIMER EVETNT REG:"
rd 0x44e10000 0xfd0


echo "Triggering GPIO0 interrupt"
wr $GPIO0_BASE $GPIO_IRQ_SET0_OFFSET 0x01
wr $GPIO0_BASE $GPIO0_IRQ_RAW_OFFSET 0x01





echo "------------------"
echo "Timer5 CAP1 value:"
rd $TIMER5_BASE "0x50"
wr $TIMER5_BASE "0x28" 0x7
echo "Timer6 CAP1 value:"
rd $TIMER6_BASE "0x50"
wr $TIMER6_BASE "0x28" 0x7


sleep 3
echo "Triggering GPIO0 interrupt"
wr $GPIO0_BASE $GPIO0_IRQ_RAW_OFFSET 0x01


echo "------------------"
echo "Timer5 CAP1 value:"
rd $TIMER5_BASE "0x50"
wr $TIMER5_BASE "0x28" 0x7
echo "Timer6 CAP1 value:"
rd $TIMER6_BASE "0x50"
wr $TIMER6_BASE "0x28" 0x7


sleep 3

echo "Triggering GPIO0 interrupt"
wr $GPIO0_BASE $GPIO_IRQ_SET0_OFFSET 0x01
wr $GPIO0_BASE $GPIO0_IRQ_RAW_OFFSET 0x01



echo "------------------"
echo "Timer5 CAP1 value:"
rd $TIMER5_BASE "0x50"
wr $TIMER5_BASE "0x28" 0x7
echo "Timer6 CAP1 value:"
rd $TIMER6_BASE "0x50"
wr $TIMER6_BASE "0x28" 0x7




