#!/bin/sh
export PRU_SDK=/home/debian/pru/pru_2.0.0B2/

echo "Compiling the pru_task.c application"
$PRU_SDK/bin/clpru --silicon_version=3 pru_task.c -i$PRU_SDK/include \
    -i$PRU_SDK/lib -z AM3359_PRU.cmd -o pru_task.out -m pru_task.map

echo "Converting the executable to a ARM object file"
$PRU_SDK/bin/hexpru $PRU_SDK/bin.cmd pru_task.out

echo "Compiling the pru_init_task.c application"
gcc pru_init_task.c -o pru_init_task -lpthread -lprussdrv

echo "Remember to load the overlay or use config-pin"
#echo "   sudo sh -c \"echo EBB-PRU-Example > $SLOTS\""
#echo "which requires you to disable the HDMI overlay, as described in Chapter 6"

