#!/bin/bash

alias dm="busybox devmem"


rd () {
	busybox devmem `printf "0x%X" $(( $1 + $2 ))`
}

wr (){
	busybox devmem `printf "0x%X" $(( $1 +  $2 ))` 32  $3
}

GPIO0_BASE="0x44e07000"
GPIO0_IRQ_RAW_OFFSET="0x24"
GPIO_IRQ_SET0_OFFSET="0x34"

echo "Triggering GPIO0 interrupt"
wr $GPIO0_BASE $GPIO_IRQ_SET0_OFFSET 0x01
wr $GPIO0_BASE $GPIO0_IRQ_RAW_OFFSET 0x01






